### ISSUE TITLE
Fix behavior when canceling a motion

### ISSUE THREAD

**Issue by adolfo-rt** [pal-robotics/play_motion#15]
This is the current output produced when a motion is canceled (timestamps removed for brevity):

```
[ WARN] [.]: controller left_arm_controller failed with err 0
[ WARN] [.]: controller head_controller failed with err 0
[ WARN] [.]: controller right_arm_controller failed with err 0
[ WARN] [.]: controller torso_controller failed with err 0
[ INFO] [.]: Motion played successfully.
[ERROR] [.]: You are attempting to call methods on an uninitialized goal handle
```

Things to look into:
- The last message suggests something fishy in the actionlib logic.
- The `Motion played successfully.` message is not correct. It should say something more like `Motion execution was canceled.`. This point might be related to the previous one.
- When a motion is canceled, we should probably discriminate between the cases of the play_motion goal being canceled, and somebody preempting our controller goals. Ideally, a single log statement could reflect that. Examples:

`Motion execution was canceled.`
`Motion execution failed. Controller: 'foo' failed with error 0.`

**Comment by po1** [comment]
This is because the final states of the controller goals are not propagated appropriately.
The internal API is doing information withholding. Maybe I can talk some sense into it.

**Comment by adolfo-rt** [comment]
> Maybe I can talk some sense into it.

Be kind
