### ISSUE TITLE
PlayMotion::run should not compute approach trajectories when it's busy

### ISSUE THREAD

**Issue by adolfo-rt** [pal-robotics/play_motion#27]
Currently, if play_motion is busy executing a motion, and a new request arrives, it will first compute an approach trajectory for the requested motion before checking if it's actually busy or not. Requests should be rejected as early as possible. I'll refactor the run method to exhibit this behavior.

**Comment by po1** [comment]
I suggest that motions should also be rejected if the planner is busy. If you agree, please make sure that the logic implements that.

**Comment by adolfo-rt** [comment]
Yes, that would be the case.

**Comment by adolfo-rt** [comment]
Fixed in #30.
