### ISSUE TITLE
exception thrown when time_from_start field of motion is integer

### ISSUE THREAD

**Issue by bmagyar** [pal-robotics/play_motion#28]
... which should be a valid use case.

To reproduce the issue change any motion the following way:

time_from_start: 1.0  -> time_from_start: 1

Example output upon execution:
[ INFO] [1394210639.559383205, 954.873000000]: sending motion 'arms_t' to controllers
terminate called after throwing an instance of 'XmlRpc::XmlRpcException'
Aborted (core dumped)

**Comment by bmagyar** [comment]
Addition: an integer in the "positions" list causes the same type of crash

**Comment by po1** [comment]
The problem comes from `xmlrpc++` overloading the typecasts and performing run-time checks. I will add a catch block for that case and silently convert an `int` to a `float`
