### ISSUE TITLE
Implement convenience move_joint script.

### ISSUE THREAD

**Issue by adolfo-rt** [pal-robotics/play_motion#33]
In another project, we have developed a convenience command-line tool called `move_joint` that allows to easily move a joint to a given position, optionally specifying the motion duration. Considering the current state of `play_motion`, it should be straightforward to reimplement this tool as a Python script that leverages `play_motion`.

The script will need to use functionality from the `motion_planning` branch, so it will be implemented there.

**Comment by adolfo-rt** [comment]
Noteworthy improvements over the existing implementation are:
- A lot less code overlap between the two projects.
- Use of the action interface of the `joint_trajectory_controller` (not the topic interface).
- `move_joint` is aware of the execution result, so we know if the motion succeeded or not.
- `move_joint` is now preemtible, i.e., <kbd>ctrl-c</kbd> will immediately abort execution of the current goal.
- If execution time is not specified, it's auto-computed (by `play_motion`) instead of defaulting to 5s.

**Comment by po1** [comment]
Has this been merged as part of #36?

**Comment by adolfo-rt** [comment]
Yes
