### ISSUE TITLE
Move messages to separate package play_motion_msgs

### ISSUE THREAD

**Issue by adolfo-rt** [pal-robotics/play_motion#9]

**Comment by po1** [comment]
Would you then advise the creation of a meta package?

**Comment by adolfo-rt** [comment]
Probably yes. The thing is that now we are starting to add more dependencies on play_motion, such as MoveIt!, which is pretty big. I don't want users of the play_motion ROS API to depend on all that.

**Comment by po1** [comment]
I'll see how git reacts when I move the whole package one layer deeper

**Comment by adolfo-rt** [comment]
As discussed in person, we could just have the two packages, play_motion and play_motion_msgs sit side by side in the repo without adding a metapackage.
